### ISSUE TITLE
Are problem files retried?

### ISSUE THREAD

**Issue by Infray** [cjmanca/plex-credits-detect#49]
While monitoring the output of the tool I've encountered 2 problem cases:

```
Detecting: /<movie>/<movie>
Black frames found from 5621.94 to 6088.94. Duration: 467.00.
PlexDB ExecuteDBCommand Database has been locked for a long time. Attempting to re-connect.
Inserting match:  from 5621.94 to 6088.94. Duration: 467.00.
```

```
FingerprintFile Exception: System.AggregateException: One or more errors occurred. (End of file)
 ---\u003e System.ApplicationException: End of file
   at SoundFingerprinting.Emy.FFmpeg.Common.ErrorExtensions.ThrowExceptionIfError(Int32 error)
   at SoundFingerprinting.Emy.FFmpeg.Demuxer.OpenInputFile(String file)
   at SoundFingerprinting.Emy.FFmpeg.Demuxer..ctor(String file, MediaType mediaType, CancellationToken cancellationToken)
   at SoundFingerprinting.Emy.AudioVideo.Data.FFmpegDataService.ReadAVTrack(String source, MediaType mediaType, Double seconds, Int32 count, AVTrackReadConfiguration avTrackReadConfiguration, CancellationToken cancellationToken)+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at SoundFingerprinting.Emy.AudioVideo.Data.FFmpegDataService.ReadTrack(String file, MediaType mediaType, Double seconds, AVTrackReadConfiguration configuration)
   at SoundFingerprinting.Emy.FFmpegAudioService.GetAudioTrack(String path, Int32 sampleRate, Double seconds)
   at SoundFingerprinting.Emy.FFmpegAudioService.ReadMonoSamplesFromFile(String path, Int32 sampleRate, Double seconds, Double startAt)
   at SoundFingerprinting.Command.FingerprintCommand.\u003c\u003ec__DisplayClass13_0.\u003cFrom\u003eb__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
```

In these cases will the file be retried on the next run, or do I need to set `recheckUndetectedOnStartup = true` for this to happen?

**Comment by cjmanca** [comment]
It won't matter - it'll happen every time for that file. I've seen that on a few files, and it happens reliably every time. Something about the file can't be read properly, I'm unsure exactly what, but it's not something I can fix. The exception is coming from a closed source area of the SoundFingerprinting library. I've previously posted issues on their github, but the maintainer basically has said he won't fix it.

It automatically skips the file, but obviously won't detect any credits for it. If you really want credits for that episode/movie, you could get an alternate version of the video.

**Comment by cjmanca** [comment]
If you see the `PlexDB ExecuteDBCommand Database has been locked for a long time. Attempting to re-connect` message a lot, I'd suggest the following steps:
1. In plex, run the "Optimize Database" command
2. After confirming that the optimize completed, close both plex and plex-credits-detect
3. Backup your plex databse to be safe
4. Run the database repair operation on the plex support page (specifically the VACUUM command)
5. Re-launch plex and PCD

I've had a few reports that the optimize/repair combo greatly reduces the database locking issues, and generally speeds things up.

**Comment by Infray** [comment]
> As for the second one (the end of file exception), it won't matter if you get it to try again - it'll happen every time for that file. I've seen that on a few files, and it happens reliably every time. Something about the file can't be read properly, I'm unsure exactly what, but it's not something I can fix. The exception is coming from a closed source area of the SoundFingerprinting library. I've previously posted issues on their github, but the maintainer basically has said he won't fix it.

If it keeps retrying and failing that's fine. I've seen a couple of these flash by while processing my library, but lost the output after the latest version was deployed (automatically by fluxcd). So if it retries and fails again I'll be able to see the problematic files in the output appear again.



> For the first one - it fixed it's self. The `PlexDB ExecuteDBCommand Database has been locked for a long time. Attempting to re-connect.` is basically a timeout, after which it tries to re-load the database and try again. The next line says it was successful.

For the one instance that I saw it, it was fixed after restarting the PCD container, but that might have been a fluke.
I'll keep the procedure you mentioned in mind though.

Thanks

**Comment by cjmanca** [comment]
> If it keeps retrying and failing that's fine. I've seen a couple of these flash by while processing my library, but lost the output after the latest version was deployed (automatically by fluxcd). So if it retries and fails again I'll be able to see the problematic files in the output appear again.

It won't automatically retry. It'll only retry if it has a need to go back to that season for some reason (more episodes added, or intros change). If you want to force it to search for things to retry, you'd need to use `recheckUndetectedOnStartup = true`
