### ISSUE TITLE
Unhandled exception. System.DllNotFoundException: 

### ISSUE THREAD

**Issue by misto1234** [cjmanca/plex-credits-detect#57]
Getting a strange error when running tool on a Mac. Any ideas on this ?

Detecting: /100 Girls (2000)/100.Girls.2000.1080p.WEBRip.x265-newzNZB-xpost.mp4
Unhandled exception. System.DllNotFoundException: Unable to load DLL 'avformat.58': The specified module could not be found.
   at FFmpeg.AutoGen.ffmpeg.LoadLibrary(String libraryName, Boolean throwException)
   at FFmpeg.AutoGen.ffmpeg.<>c.<.cctor>b__6_0(String libraryName)
   at FFmpeg.AutoGen.ffmpeg.<>c.<.cctor>b__6_318()
   at FFmpeg.AutoGen.ffmpeg.avformat_alloc_context()
   at plexCreditsDetect.ffmpeghelper.GetDuration(String path) in C:\Documents\projects\plex-credits-detect\plex-credits-detect\ffmpeghelper.cs:line 23
   at plexCreditsDetect.Episode.get_duration() in C:\Documents\projects\plex-credits-detect\plex-credits-detect\Episode.cs:line 525
   at plexCreditsDetect.Scanner.GetSearchDuration(Episode ep, Settings settings, Boolean isCredits) in C:\Documents\projects\plex-credits-detect\plex-credits-detect\Scanner.cs:line 314
   at plexCreditsDetect.Scanner.GetTimings(Episode ep, Settings settings, Boolean isCredits, Segment seg) in C:\Documents\projects\plex-credits-detect\plex-credits-detect\Scanner.cs:line 201
   at plexCreditsDetect.Scanner.DetectSilence(Episode ep, Settings settings) in C:\Documents\projects\plex-credits-detect\plex-credits-detect\Scanner.cs:line 1130
   at plexCreditsDetect.Scanner.HandleInsert(Episode ep, Settings settings, Int32 detected) in C:\Documents\projects\plex-credits-detect\plex-credits-detect\Scanner.cs:line 967
   at plexCreditsDetect.Scanner.ScanDirectory(String path, Settings settings) in C:\Documents\projects\plex-credits-detect\plex-credits-detect\Scanner.cs:line 725
   at plexCreditsDetect.Program.Main(String[] args) in C:\Documents\projects\plex-credits-detect\plex-credits-detect\Program.cs:line 131
Abort trap: 6

**Comment by cjmanca** [comment]
Check in the "plex-credits-detect" directory to see if the "avformat-58.dll" is in there. It's included in the release, so assuming you extracted the whole directory it should be. If not, then re-download and re-extract it.

**Comment by misto1234** [comment]
Yeah ... extracted again and the file is there. Not sure what's going on with it.. if you want to message me I can provide logs ... would be greatly appreciated!
